name: GitHub actions are building the repo for my ROS2 project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2 Jazzy
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository universe
          sudo apt update && sudo apt install curl -y
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt upgrade
          sudo apt install ros-jazzy-desktop
          sudo apt install ros-jazzy-ros-base

      - name: Build workspace
        run: |
          cd /home/cuongchutan/cuong_internBMW_ros2_jazzy
          colcon build --merge-install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip3 install -r sine_wave/requirements.txt

      - name: Run tests
        run: |
          pytest
