name: GitHub actions apply linting and formatting rules for my ROS2 project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2 Jazzy
        run: |
          sudo sh -c 'echo "deb [arch=amd64] http://packages.osrfoundation.org/debian jazzy-stable main" > /etc/apt/sources.list.d/ros2-jazzy.list'
          sudo apt-get update
          sudo apt-get install -y ros-jazzy-ros-core ros-jazzy-ros-base ros-jazzy-rqt ros-jazzy-rqt-plot
          source /opt/ros/jazzy/setup.bash

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip3 install -r src/sine_wave/requirements.txt

      - name: Run linters for sine_wave
        uses: ros-tooling/action-ros-lint@master
        with:
          linter: copyright
          package-name: sine_wave

      - name: Run linters for grayscale_image
        uses: ros-tooling/action-ros-lint@master
        with:
          linter: copyright
          package-name: grayscale_image

      - name: Run formatting for C++ files with clang-format
        run: |
          find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -i

      - name: Run formatting for Python files with black
        run: |
          black .
          